### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Johnnywang92** [cmbi/metadome#42]
when I run the install command on MAC Mojave (Python 2.7.10), get error message as following: 

Starting metadome_redis_1    ... done
Starting metadome_rabbitmq_1 ... done
Creating metadome_db_1       ... error

ERROR: for metadome_db_1  Cannot create container for service db: b"error while mounting volume with options: type='none' device='<ABSOLUTE PATH>' o='bind': no such file or directory"

ERROR: for db  Cannot create container for service db: b"error while mounting volume with options: type='none' device='<ABSOLUTE PATH>' o='bind': no such file or directory"
ERROR: Encountered errors while bringing up the project.

Any suggestion?

**Comment by laurensvdwiel** [comment]
Dear @Johnnywang92 ,

I believe you have not configured the <absolute path> in the docker-compose.yml file.
I have seen that this was incorrectly specified in the installation part of the readme.md, I have changed this to point to the correct line numbers in f7797f0c3caf864dfa583d14319941ac5cd7e047. Can you verify it now works?

**Comment by Johnnywang92** [comment]
![screen shot 2019-01-09 at 9 58 54 am](https://user-images.githubusercontent.com/13830258/50873679-e6b74400-13fb-11e9-9f87-97b28ed243ab.png)
Thank you for your answer. I tried a lot of times to modify the docker-compose.yml file, and re-run the install script, but still not work.The error message is [ERROR: for metadome_db_1  Cannot create container for service db: b"error while mounting volume with options: type='none' device='</Users/yifanwang/Test/data/meta_data/>' o='bind': no such file or directory"]

**Comment by laurensvdwiel** [comment]
Dear @Johnnywang92 ,

The device folders are incorrectly specified in your docker-compose.yml, please remove the '<' and '>'.
Here is an example of my local test docker-compose:

```
volumes:
   data: 
      driver_opts:
        type: none
        # Please set the 'device' here to a local folder you are okay with MetaDome to create additional files and folders
        device: /usr/data
        o: bind
```
